#!/usr/bin/env python3
from __future__ import annotations

import os
import secrets
import shutil
import stat
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT_DIR / "backend"
DATA_DIR = ROOT_DIR / ".data"
PGDATA = DATA_DIR / "postgres"
HBA_PATH = PGDATA / "pg_hba.conf"
BACKUP_DIR = DATA_DIR / "backups"
ENV_PATH = DATA_DIR / "local-db.env"
VENV_PYTHON = ROOT_DIR / ".venv" / "bin" / "python"
VENV_DIR = ROOT_DIR / ".venv"
DB_NAME = "scenic_ticket"
DB_PORT = "15432"
ADMIN_ROLE = os.environ.get("USER", "dingdexin")
APP_ROLE = "scenic_app"
OWNER_ROLE = "scenic_owner"
READONLY_ROLE = "scenic_readonly"

if __name__ == "__main__" and VENV_PYTHON.exists() and Path(sys.prefix).resolve() != VENV_DIR.resolve():
    os.execv(str(VENV_PYTHON), [str(VENV_PYTHON), str(Path(__file__).resolve()), *sys.argv[1:]])

if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

import psycopg  # noqa: E402
from psycopg import sql  # noqa: E402


def run(command: list[str], *, env: dict[str, str] | None = None, expect_success: bool = True) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        command,
        cwd=ROOT_DIR,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if expect_success and result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "command failed"
        raise RuntimeError(f"{command[0]} failed: {detail}")
    return result


def harden_hba(text: str) -> str:
    rules = {
        ("local", "all", "all"): "local   all             all                                     peer",
        ("host", "all", "all", "127.0.0.1/32"): "host    all             all             127.0.0.1/32            scram-sha-256",
        ("host", "all", "all", "::1/128"): "host    all             all             ::1/128                 scram-sha-256",
        ("local", "replication", "all"): "local   replication     all                                     peer",
        (
            "host",
            "replication",
            "all",
            "127.0.0.1/32",
        ): "host    replication     all             127.0.0.1/32            scram-sha-256",
        ("host", "replication", "all", "::1/128"): "host    replication     all             ::1/128                 scram-sha-256",
    }
    found: set[tuple[str, ...]] = set()
    output: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            output.append(line)
            continue
        parts = stripped.split()
        key = tuple(parts[:3]) if parts[0] == "local" else tuple(parts[:4])
        replacement = rules.get(key)
        if replacement is None:
            output.append(line)
            continue
        found.add(key)
        output.append(replacement)
    missing = set(rules) - found
    if missing:
        raise RuntimeError(f"pg_hba.conf is missing expected local rules: {sorted(missing)}")
    return "\n".join(output) + "\n"


def env_text(app_password: str, readonly_password: str) -> str:
    return (
        "# Generated by scripts/harden-local-database.py; do not commit.\n"
        "DB_HOST=127.0.0.1\n"
        f"DB_PORT={DB_PORT}\n"
        f"DB_NAME={DB_NAME}\n"
        f"DB_USER={APP_ROLE}\n"
        f"DB_PASSWORD={app_password}\n"
        "DB_SSLMODE=disable\n"
        f"READONLY_DB_USER={READONLY_ROLE}\n"
        f"READONLY_DB_PASSWORD={readonly_password}\n"
    )


def atomic_write(path: Path, content: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent, text=True)
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary_path, mode)
        temporary_path.replace(path)
    except Exception:
        temporary_path.unlink(missing_ok=True)
        raise


def ensure_role(connection: psycopg.Connection, role: str, *, can_login: bool) -> None:
    exists = connection.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (role,)).fetchone()
    if not exists:
        connection.execute(
            sql.SQL("CREATE ROLE {} {}").format(
                sql.Identifier(role),
                sql.SQL("LOGIN") if can_login else sql.SQL("NOLOGIN"),
            )
        )
    connection.execute(
        sql.SQL(
            "ALTER ROLE {} {} NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS"
        ).format(sql.Identifier(role), sql.SQL("LOGIN") if can_login else sql.SQL("NOLOGIN"))
    )


def apply_roles(app_password: str, readonly_password: str) -> None:
    with psycopg.connect(dbname=DB_NAME, user=ADMIN_ROLE, port=DB_PORT) as connection:
        connection.execute("SET password_encryption = 'scram-sha-256'")
        ensure_role(connection, OWNER_ROLE, can_login=False)
        ensure_role(connection, APP_ROLE, can_login=True)
        ensure_role(connection, READONLY_ROLE, can_login=True)
        connection.execute(
            sql.SQL("ALTER ROLE {} PASSWORD {}").format(sql.Identifier(APP_ROLE), sql.Literal(app_password))
        )
        connection.execute(
            sql.SQL("ALTER ROLE {} PASSWORD {}").format(
                sql.Identifier(READONLY_ROLE),
                sql.Literal(readonly_password),
            )
        )
        connection.execute(sql.SQL("ALTER DATABASE {} OWNER TO {}").format(sql.Identifier(DB_NAME), sql.Identifier(OWNER_ROLE)))
        connection.execute(sql.SQL("REASSIGN OWNED BY {} TO {}").format(sql.Identifier(APP_ROLE), sql.Identifier(OWNER_ROLE)))
        connection.execute(sql.SQL("ALTER SCHEMA public OWNER TO {}").format(sql.Identifier(OWNER_ROLE)))

        connection.execute(sql.SQL("REVOKE ALL ON DATABASE {} FROM PUBLIC").format(sql.Identifier(DB_NAME)))
        connection.execute(sql.SQL("REVOKE ALL ON DATABASE {} FROM {}, {}").format(
            sql.Identifier(DB_NAME), sql.Identifier(APP_ROLE), sql.Identifier(READONLY_ROLE)
        ))
        connection.execute(sql.SQL("GRANT CONNECT ON DATABASE {} TO {}, {}").format(
            sql.Identifier(DB_NAME), sql.Identifier(APP_ROLE), sql.Identifier(READONLY_ROLE)
        ))

        connection.execute(sql.SQL("REVOKE ALL ON SCHEMA public FROM PUBLIC, {}, {}").format(
            sql.Identifier(APP_ROLE), sql.Identifier(READONLY_ROLE)
        ))
        connection.execute(sql.SQL("GRANT USAGE ON SCHEMA public TO {}, {}").format(
            sql.Identifier(APP_ROLE), sql.Identifier(READONLY_ROLE)
        ))
        connection.execute(sql.SQL("REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC, {}, {}").format(
            sql.Identifier(APP_ROLE), sql.Identifier(READONLY_ROLE)
        ))
        connection.execute(sql.SQL("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO {}").format(
            sql.Identifier(APP_ROLE)
        ))
        connection.execute(sql.SQL("GRANT SELECT ON ALL TABLES IN SCHEMA public TO {}").format(
            sql.Identifier(READONLY_ROLE)
        ))
        connection.execute(sql.SQL("REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC, {}, {}").format(
            sql.Identifier(APP_ROLE), sql.Identifier(READONLY_ROLE)
        ))
        connection.execute(sql.SQL("GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO {}").format(
            sql.Identifier(APP_ROLE)
        ))
        connection.execute(sql.SQL("ALTER DEFAULT PRIVILEGES FOR ROLE {} IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC").format(
            sql.Identifier(OWNER_ROLE)
        ))
        connection.execute(sql.SQL(
            "ALTER DEFAULT PRIVILEGES FOR ROLE {} IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO {}"
        ).format(sql.Identifier(OWNER_ROLE), sql.Identifier(APP_ROLE)))
        connection.execute(sql.SQL(
            "ALTER DEFAULT PRIVILEGES FOR ROLE {} IN SCHEMA public GRANT SELECT ON TABLES TO {}"
        ).format(sql.Identifier(OWNER_ROLE), sql.Identifier(READONLY_ROLE)))
        connection.execute(sql.SQL(
            "ALTER DEFAULT PRIVILEGES FOR ROLE {} IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO {}"
        ).format(sql.Identifier(OWNER_ROLE), sql.Identifier(APP_ROLE)))


def psql(role: str, statement: str, *, password: str | None = None) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env.pop("PGPASSWORD", None)
    if password is not None:
        env["PGPASSWORD"] = password
    return run(
        [
            "psql",
            "-X",
            "-w",
            "-h",
            "127.0.0.1",
            "-p",
            DB_PORT,
            "-U",
            role,
            "-d",
            DB_NAME,
            "-v",
            "ON_ERROR_STOP=1",
            "-c",
            statement,
        ],
        env=env,
        expect_success=False,
    )


def verify(app_password: str, readonly_password: str) -> None:
    if psql(APP_ROLE, "SELECT 1").returncode == 0:
        raise RuntimeError("passwordless scenic_app TCP login unexpectedly succeeded")
    if psql(APP_ROLE, "SELECT 1", password=app_password).returncode != 0:
        raise RuntimeError("scenic_app password login failed")
    if psql(APP_ROLE, "UPDATE visitor SET updated_at = updated_at WHERE FALSE", password=app_password).returncode != 0:
        raise RuntimeError("scenic_app required UPDATE permission is missing")
    if psql(APP_ROLE, "CREATE TABLE public.__role_hardening_probe(id integer)", password=app_password).returncode == 0:
        with psycopg.connect(dbname=DB_NAME, user=ADMIN_ROLE, port=DB_PORT) as connection:
            connection.execute("DROP TABLE IF EXISTS public.__role_hardening_probe")
        raise RuntimeError("scenic_app unexpectedly has CREATE TABLE permission")
    if psql(READONLY_ROLE, "SELECT 1 FROM visitor LIMIT 1", password=readonly_password).returncode != 0:
        raise RuntimeError("scenic_readonly SELECT failed")
    if psql(
        READONLY_ROLE,
        "UPDATE visitor SET updated_at = updated_at WHERE FALSE",
        password=readonly_password,
    ).returncode == 0:
        raise RuntimeError("scenic_readonly unexpectedly has UPDATE permission")

    env = os.environ.copy()
    env.update(
        {
            "DB_HOST": "127.0.0.1",
            "DB_PORT": DB_PORT,
            "DB_NAME": DB_NAME,
            "DB_USER": APP_ROLE,
            "DB_PASSWORD": app_password,
            "DB_SSLMODE": "disable",
            "PYTHONPATH": str(BACKEND_DIR),
        }
    )
    check = run(
        [
            str(VENV_PYTHON),
            "-c",
            "from app.core.db import connect_db, ping_database; "
            "c = connect_db(); assert ping_database(c); c.close()",
        ],
        env=env,
        expect_success=False,
    )
    if check.returncode != 0:
        raise RuntimeError("FastAPI database connection check failed")


def main() -> int:
    if not PGDATA.is_dir() or not HBA_PATH.is_file():
        raise RuntimeError(f"local PostgreSQL data directory not found: {PGDATA}")
    run(["pg_ctl", "-D", str(PGDATA), "status"])

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    dump_path = BACKUP_DIR / f"{DB_NAME}-before-role-hardening-{timestamp}.dump"
    hba_backup_path = BACKUP_DIR / f"pg_hba-before-role-hardening-{timestamp}.conf"
    run(["pg_dump", "-Fc", "-p", DB_PORT, "-U", ADMIN_ROLE, "-d", DB_NAME, "-f", str(dump_path)])
    shutil.copy2(HBA_PATH, hba_backup_path)

    app_password = secrets.token_urlsafe(32)
    readonly_password = secrets.token_urlsafe(32)
    hardened_hba = harden_hba(HBA_PATH.read_text(encoding="utf-8"))
    apply_roles(app_password, readonly_password)
    atomic_write(ENV_PATH, env_text(app_password, readonly_password), stat.S_IRUSR | stat.S_IWUSR)
    atomic_write(HBA_PATH, hardened_hba, stat.S_IRUSR | stat.S_IWUSR)
    run(["pg_ctl", "-D", str(PGDATA), "reload"])

    try:
        verify(app_password, readonly_password)
    except Exception:
        shutil.copy2(hba_backup_path, HBA_PATH)
        run(["pg_ctl", "-D", str(PGDATA), "reload"])
        raise

    print("Local database hardening completed.")
    print(f"Credentials: {ENV_PATH.relative_to(ROOT_DIR)} (mode 0600)")
    print(f"Database backup: {dump_path.relative_to(ROOT_DIR)}")
    print(f"Authentication backup: {hba_backup_path.relative_to(ROOT_DIR)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
